In [32]:
import numpy as np

In [33]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype='float32')
print(b)

[1 2 3] [[1. 2. 3.]
 [4. 5. 6.]]


In [35]:
#get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [36]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
#get type
print(a.dtype)
print(b.dtype)


int32
float32
12
24


In [38]:
#get size
print(a.itemsize)
print(b.itemsize)

4
4


In [41]:
#get totalsie
print(a.size)
print(b.size)
print(a.nbytes)
print(b.nbytes)

3
6
12
24
