In [65]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [68]:
#get a specific element [row, column]
a[1, 1]

np.int64(9)

In [33]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
#get a specific column
a[:,0]

array([1, 8])

In [66]:

#getting a little more fancy [startindex:endindex:stepsize]
a[0,0:7:1]


array([1, 2, 3, 4, 5, 6, 7])

In [71]:
print(a[0,0:7:1])

[1 2 3 4 5 6 7]


In [46]:
#change elements
a[0,0] = 100001
print(a)

a[:,2] = [100,200]
print(a)

[[100001      2    100      4      5      6      7]
 [     8      9    200     11     12     13     14]]
[[100001      2    100      4      5      6      7]
 [     8      9    200     11     12     13     14]]


In [70]:
b = np.array([[[1,2],[4,5]],[[7,8],[10,11]]])
print(b)
b[0,0,0]

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


np.int64(1)

In [73]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[7 8]
  [8 8]]]
