In [2]:
import numpy as np


In [3]:
np.zeros((2,5,5,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [4]:
np.full((2,2,2,4), 111)

array([[[[111, 111, 111, 111],
         [111, 111, 111, 111]],

        [[111, 111, 111, 111],
         [111, 111, 111, 111]]],


       [[[111, 111, 111, 111],
         [111, 111, 111, 111]],

        [[111, 111, 111, 111],
         [111, 111, 111, 111]]]])

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
#any other number(full_like)
np.full_like(a,444)


array([[444, 444, 444, 444, 444, 444, 444],
       [444, 444, 444, 444, 444, 444, 444]])

In [7]:
#random decimal numbers
np.random.rand(4,4)

array([[0.12545695, 0.5292843 , 0.01602983, 0.13421161],
       [0.45644313, 0.03681739, 0.0410217 , 0.07724506],
       [0.57543083, 0.30515231, 0.13345463, 0.76871421],
       [0.23365509, 0.66106334, 0.03949898, 0.14852114]])

In [8]:
np.random.random_sample((a.shape))

array([[0.00669538, 0.06056053, 0.50810092, 0.81205712, 0.04223672,
        0.77996148, 0.57825464],
       [0.82572576, 0.78749589, 0.23536293, 0.27336894, 0.26919764,
        0.38259708, 0.42275473]])

In [9]:
np.random.randint(0,999,size=(4,4))

array([[786, 788, 604,   2],
       [213, 761,  28, 439],
       [417,  18, 302, 421],
       [387, 518, 354, 421]], dtype=int32)

In [10]:
#random interger values
np.random.randint(0,4,a.shape)

array([[3, 1, 3, 3, 1, 1, 1],
       [3, 2, 2, 3, 2, 0, 2]], dtype=int32)

In [17]:
##random integer number
np.random.randint(1,10,size=(5,5))

array([[6, 8, 3, 6, 4],
       [5, 1, 9, 1, 9],
       [4, 2, 2, 4, 5],
       [2, 6, 5, 3, 8],
       [1, 3, 4, 3, 3]], dtype=int32)

In [18]:
#indentity matrinx
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
#repeat an array
a = np.array([[1,2,3],[4,5,6]])
np.repeat(a,3,axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [30]:
#problem_1
a = np.ones((5,5))
print(a)
b = np.zeros((3,3))
print(b)
b[1,1]=9
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [34]:
a[1:4,1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
a = np.array([1,2,3])
b = a.copy()
print(b)
b[0]=100
print(a)    

[1 2 3]
[1 2 3]


In [48]:
#mathematics
b=a+2
c=a-2
d=a*2
e=a%2
f=a/2
g=a**2
print(b)
print(c)  
print(d)
print(e)
print(f)
print(g)  
h=np.sin(a)
i=np.cos(a) 
print(h)
print(i)              

[3 4 5]
[-1  0  1]
[2 4 6]
[1 0 1]
[0.5 1.  1.5]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [51]:
#linear algebra
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print(b)
#matrix multiplication
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [60]:
c = np.identity(4)
print(c)
d = np.linalg.det(c)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
1.0


In [65]:
#statics 
stats = np.array([[1,2,3],[4,5,6]])
a = np.min(stats)
b = np.max(stats)
c = np.sum(stats)
d = np.min(stats,axis=1)
e = np.max(stats,axis=0)
f = np.sum(stats,axis=0)
print(a)
print(b)    
print(c)
print(d)
print(e)
print(f)


1
6
21
[1 4]
[4 5 6]
[5 7 9]


In [67]:
#reorganizing arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [71]:
#vertically stacking vectors
v1 = np.array([1,2,3,4]) 
v2 = np.array([5,6,7,8,])
np.vstack((v1,v2,v2,v2,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [75]:
#horizontal stacking
v1 = np.array([1,2,3,4]) 
v2 = np.array([5,6,7,8,])
a = np.hstack((v1,v2,v2,v2,v1))
#a.reshape(5,4)
print(a)    

[1 2 3 4 5 6 7 8 5 6 7 8 5 6 7 8 1 2 3 4]


In [90]:
#Miscellaneous
#Load Data from File
filedata = np.loadtxt('file.txt', delimiter=',')
#filedata = np.genfromtxt('file.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [91]:
#boolean masking and advanced indexing
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [92]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [100]:
a = filedata[(filedata > 50) & (filedata < 100)]
print(a)
b = (((filedata > 50) & (filedata < 100)))
print(b)
c = (~((filedata > 50) & (filedata < 100))) 
print(c,end = "")
d = filedata[filedata == 0]
print(d)

[75 75 55 78 76 88]
[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]][0 0 0]
